SELECT 
 I.[NAME] AS DS_INDICE
 ,O.[NAME] AS DS_TABELA
 ,CASE WHEN IC.[KEY_ORDINAL] > 0 AND IC.[IS_DESCENDING_KEY] = 0 THEN C.[NAME] ELSE '' END AS DS_COLUNAS
 ,CASE WHEN IC.[KEY_ORDINAL] > 0 AND IC.[IS_DESCENDING_KEY] = 1 THEN C.[NAME] ELSE '' END AS DS_COLUNASDESC
 ,CASE WHEN IC.[IS_INCLUDED_COLUMN] > 0 AND IC.[IS_DESCENDING_KEY] = 0 THEN C.[NAME] ELSE '' END AS DS_COLUNASINCLUDE
 ,CASE WHEN IC.[IS_INCLUDED_COLUMN] > 0 AND IC.[IS_DESCENDING_KEY] = 1 THEN C.[NAME] ELSE '' END AS DS_COLUNASINCLUDEDESC
FROM
 SYS.[INDEXES] I
LEFT JOIN SYS.[INDEX_COLUMNS] IC ON IC.[INDEX_ID] = I.[INDEX_ID]
LEFT JOIN SYS.[COLUMNS] C ON C.[COLUMN_ID] = IC.[COLUMN_ID] AND C.[OBJECT_ID] = IC.[OBJECT_ID]
LEFT JOIN SYS.[OBJECTS] O ON O.[OBJECT_ID] = I.[OBJECT_ID] 
WHERE
 I.[NAME] = 'IX_TB_CADUNICO_DS_CEP'
ORDER BY IC.[KEY_ORDINAL]