CREATE TABLE CLIENTES(ID_CLIENTE INT, NOME CHAR(10))
INSERT INTO CLIENTES VALUES(1, 'JOÃO')
INSERT INTO CLIENTES VALUES(2, 'MARIA')

CREATE TABLE MESES (MES CHAR(3))
INSERT INTO MESES VALUES('JAN')
INSERT INTO MESES VALUES('FEV')
INSERT INTO MESES VALUES('MAR')
INSERT INTO MESES VALUES('ABR')
INSERT INTO MESES VALUES('MAI')
INSERT INTO MESES VALUES('JUN')

CREATE TABLE PRODUTOS(PK_ID CHAR(3), VL_PRECO NUMERIC(14,2))
INSERT INTO PRODUTOS VALUES('001', 150)
INSERT INTO PRODUTOS VALUES('002', 70)
INSERT INTO PRODUTOS VALUES('003', 50)
INSERT INTO PRODUTOS VALUES('004', 90)

CREATE TABLE VENDAS(FK_CLIENTE INT, FK_PRODUTO CHAR(3), MES_VENDA CHAR(3) )
INSERT INTO VENDAS VALUES(2, '003', 'JAN')
INSERT INTO VENDAS VALUES(2, '002', 'JAN')
INSERT INTO VENDAS VALUES(1, '001', 'JAN')
INSERT INTO VENDAS VALUES(1, '004', 'JAN')
INSERT INTO VENDAS VALUES(1, '003', 'FEV')
INSERT INTO VENDAS VALUES(2, '004', 'FEV')
INSERT INTO VENDAS VALUES(2, '001', 'MAR')
INSERT INTO VENDAS VALUES(2, '004', 'MAR')

SELECT DISTINCT 
	CLI.ID_CLIENTE
	,PRO.PK_ID AS PRODUTO
	,MES.MES
	,CASE WHEN VEN.FK_PRODUTO IS NULL THEN 'NÃO' ELSE 'SIM' END AS COMPRADO
FROM CLIENTES CLI
LEFT JOIN PRODUTOS PRO ON 1=1
LEFT JOIN MESES MES ON 1=1
LEFT JOIN VENDAS VEN ON VEN.FK_CLIENTE = CLI.ID_CLIENTE AND PRO.PK_ID = VEN.FK_PRODUTO AND VEN.MES_VENDA = MES.MES
ORDER BY ID_CLIENTE, MES, PRODUTO

-- Volpe
SELECT DISTINCT
	CAD.PK_ID CLIENTE
	,PRO.PK_ID PRODUTO
	,MONTH(MES.DT_MES) MES
	,CASE WHEN VEN.FK_PRODUTO IS NOT NULL THEN 1 ELSE 0 END TG_COMPRADO
FROM TB_CADUNICO CAD
LEFT JOIN TB_PRODUTOS PRO ON PRO.PK_ID LIKE '0%' AND PRO.TG_INATIVO = 0
LEFT JOIN TB_MESES MES ON YEAR(MES.DT_MES) = 2009
LEFT JOIN VW_VENDAS VEN ON VEN.FK_CADUNICO = CAD.PK_ID AND VEN.FK_PRODUTO = PRO.PK_ID AND MONTH(VEN.DT_REFERENCIA) = MONTH(MES.DT_MES)
WHERE CAD.FK_TIPO = 1
ORDER BY CLIENTE, MES, PRODUTO