-- Retorna qtd de registros no cursor

@@CURSOR_ROWS

-- Cria cursor temporário que somente é apagado apos desconectar sessão

SELECT
	*
INTO CURSOR
	#TMPTESTE
FROM
	TB_CADUNICO

SELECT * FROM #TMPTESTE

-- Cria tabela temporária manualmente
CREATE TABLE #TMPTESTE(CAMPOS …)



-- Tabela temporária

DECLARE @TABALUNOS TABLE(PK_ID INT, DS_NOME CHAR(50))
INSERT INTO @TABALUNOS VALUES (1, 'THIAGO')
INSERT INTO @TABALUNOS VALUES (2, 'JOAO')
INSERT INTO @TABALUNOS VALUES (2, 'MARIA')

DECLARE @TABNOTAS TABLE(PK_ID INT, CD_BIMESTRE INT, VL_NOTA NUMERIC(5,2), FK_FUNCIONARIO INT)
INSERT INTO @TABNOTAS VALUES (1, 1, 8.5, 1)
INSERT INTO @TABNOTAS VALUES (2, 2, 7.2, 1)
INSERT INTO @TABNOTAS VALUES (3, 3, 7.5, 1)
INSERT INTO @TABNOTAS VALUES (4, 4, 9.0, 1)

SELECT
	ALU.PK_ID,
	ALU.DS_NOME,
	NOTA.CD_BIMESTRE,
	NOTA.VL_NOTA
FROM
	@TABALUNOS ALU
LEFT JOIN
	@TABNOTAS NOTA ON NOTA.FK_FUNCIONARIO = ALU.PK_ID

