-- Exibir constraints criadas
SELECT
	CON.OBJECT_ID AS CONSTRAINT_ID,
	CON.NAME AS CONSTRAINT_NAME,
	TAB.NAME AS TABELAPRINC_NAME,
	REF.NAME AS TABELAREF_NAME,
	CON.CREATE_DATE AS DT_CRIACAO,
	CON.MODIFY_DATE AS DT_MODIFICACAO
FROM
	SYS.FOREIGN_KEYS CON
LEFT JOIN SYS.OBJECTS TAB ON TAB.OBJECT_ID = CON.PARENT_OBJECT_ID
LEFT JOIN SYS.OBJECTS REF ON REF.OBJECT_ID = CON.REFERENCED_OBJECT_ID
