USE MASTER
GO

SET NOCOUNT ON
DECLARE @NAME AS VARCHAR(512),
		@CMD AS VARCHAR(1024),
		@DS_TRIGGER AS VARCHAR(8000),
		@OBJ_ID INT
DECLARE CurDataBase CURSOR FAST_FORWARD FOR
SELECT TOP 10
	NAME
FROM
	SYSDATABASES
WHERE 
	NAME LIKE 'VOLPE%'
OPEN CurDataBase
FETCH NEXT FROM CurDataBase INTO @NAME
WHILE (@@FETCH_STATUS = 0)
	BEGIN
		CREATE TABLE #TMPOBJ (OBJ_ID INT, DS_TRIGGER VARCHAR(8000))
		SET @CMD = 'DECLARE @OBJ_ID AS INT SET @OBJ_ID = object_id(''' + @name + '.dbo.tr_atualizarsaldos'''+') INSERT #TMPOBJ (OBJ_ID) VALUES (@OBJ_ID)'
		EXEC(@CMD)
		SET @OBJ_ID = (SELECT OBJ_ID FROM #TMPOBJ)
		IF ( NOT @OBJ_ID IS NULL )
			BEGIN
				SET @CMD = 'UPDATE #TMPOBJ SET DS_TRIGGER = (SELECT [1] + [2] FROM (SELECT cast(text as varchar(4000)) as text, colid FROM '+@NAME+'.dbo.syscomments where id=' + CAST(@OBJ_ID AS CHAR(10))+') AS SourceTable PIVOT (max(text) for colid in ( [1],[2])) AS PivotTable)'
				EXEC(@CMD)
				SET @DS_TRIGGER = (SELECT DS_TRIGGER FROM #TMPOBJ)
				PRINT '** ' + @NAME + ' **'
				PRINT @DS_TRIGGER
				PRINT '*'
			END
		DROP TABLE #TMPOBJ
		FETCH NEXT FROM CurDataBase INTO @NAME
	END
CLOSE CurDataBase
DEALLOCATE CurDataBase
