SELECT DB_NAME() -- NOME DO BANCO CONECTADO
XP_LOGININFO -- INFORMAÇÕES DOS USUÁRIOS
SP_DATABASES -- MOSTRA DATABASES CRIADAS 
SP_DATATYPE_INFO -- MOSTRA TIPO DOS CAMPOS
SP_MONITOR -- DADOS PARA MONITORAÇÃO DO SERVIDOR
SP_TABLES -- MOSTRA TABELAS DO BANCO DE DADOS ATUAL
SP_HELPTEXT -- EXIBE CÓDIGO DA VIEW, CÓDIDO DA TRIGGER E ETC
SP_MSFOREACHTABLE "PRINT '?'" -- EXIBE TODAS AS TABELAS E EXECUTA CODIGO PASSADO
SP_WHO -- MOSTRA POOL DE CONEXÕES COM DADOS BÁSICOS
SP_WHO2 -- MOSTRA POOL DE CONEXÕES COM DADOS AVANÇADOS
SP_CONFIGURE -- MOSTRA CONFIGURAÇÕES DO SERVIDOR (MAX MEMORIA, MAX TRÁFEGO E ETC)

BULK INSERT -- INSERE DADOS A PARTIR DE UM ARQUIVO
EX:BULK INSERT TABELA
   FROM 'f:\arquivo.txt'
   WITH
     (
        FIELDTERMINATOR =' |',
        ROWTERMINATOR = '\n',
        FIRE_TRIGGERS
      )
