--ROWNUM SQL 2000
DECLARE @TESTE TABLE(PK_ID INT, DS_FANTASIA VARCHAR(50), ROWNUM INTEGER IDENTITY(1,1))
INSERT INTO @TESTE SELECT PK_ID, DS_FANTASIA FROM TB_CADUNICO
SELECT
	*
FROM
	@TESTE

--ROWNUM SQL 2005
SELECT ROW_NUMBER() OVER (ORDER BY PK_ID) AS ROWNUM, PK_ID, DS_FANTASIA FROM TB_CADUNICO ORDER BY PK_ID
