-- Funções e variáveis do sistema
SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('TB_CADUNICO')
SELECT OBJECT_NAME(OBJECT_ID) AS TABLE_NAME,* FROM SYS.COLUMNS 

-- Tabela
	SELECT
		TB.NAME AS Tabela,
		'0' AS NR_GERADO
	FROM sysobjects AS TB
	WHERE TB.XTYPE = 'u' AND TB.NAME <> 'dtproperties'
	ORDER BY TB.NAME 

-- Campos, tipo e tamanho
	SELECT
		RTRIM(TB.NAME) AS Tabela,
		RTRIM(COL.NAME) AS Campo,
		TIP.NAME AS Tipo,
		CASE WHEN TIP.NAME = 'numeric' THEN '('+ LTRIM(STR(COL.XPREC)) +','+ LTRIM(STR(COL.XSCALE))+')' ELSE
		'('+LTRIM(STR(COL.LENGTH)) +')' END as Tamanho,
		CASE WHEN col.ISNULLABLE =1 THEN 'NULL' ELSE 'NOT NULL' END AS NAONULL,
		COL.COLSTAT
	FROM sysobjects AS TB
	LEFT JOIN syscolumns AS COL ON
		COL.ID=TB.ID
	LEFT JOIN systypes AS TIP ON
		TIP.XTYPE=COL.XTYPE
	WHERE TB.XTYPE='u' AND TB.NAME <> 'dtproperties' AND NOT TIP.NAME = 'sysname'
	ORDER BY TB.NAME	

-- Sequencia
	SELECT
		RTRIM(LOWER(TB.NAME))+ '_s' AS sequencia,
		COL.COLSTAT,
		'0' AS NR_GERADO
	FROM sysobjects AS TB
	LEFT JOIN syscolumns AS COL ON
		COL.ID=TB.ID
	WHERE TB.XTYPE='u' AND TB.NAME <> 'dtproperties' and COL.COLSTAT=1
	ORDER BY TB.NAME	

-- Index
	SELECT
		COL.NAME AS CAMPO,
		IND.NAME AS INDEXES,
		TB.NAME AS TABELA,
		'0' AS NR_GERADO
	FROM SYSINDEXES AS IND
	LEFT JOIN SYSINDEXKEYS AS KEYS ON IND.INDID=KEYS.INDID AND KEYS.ID=IND.ID
	LEFT JOIN SYSCOLUMNS AS COL ON COL.COLID=KEYS.COLID AND COL.ID = IND.ID
	LEFT JOIN SYSOBJECTS AS TB ON TB.ID=IND.ID
	WHERE NOT COL.NAME IS NULL AND TB.TYPE = 'U' AND TB.NAME <> 'dtproperties' AND NOT IND.NAME LIKE '_WA_Sys_%'
	ORDER BY TB.NAME

-- Chave primária
	SELECT
		ISNULL(UPPER(CON.NAME),'') AS CHAVE,
		ISNULL(UPPER(TB.NAME),'') AS TABELA,
		ISNULL(UPPER(COL.NAME),'') AS CAMPO,
		'0' AS NR_GERADO
	FROM
		SYSOBJECTS AS CON
	LEFT JOIN SYSOBJECTS AS TB ON
		TB.ID=CON.PARENT_OBJ
	LEFT JOIN SYSINDEXKEYS AS COD ON
		COD.ID=CON.PARENT_OBJ AND COD.INDID = 1
	LEFT JOIN SYSCOLUMNS AS COL ON
		COL.COLORDER=COD.COLID AND COL.ID=CON.PARENT_OBJ
	WHERE CON.XTYPE = 'PK' AND TB.NAME <> 'dtproperties'
	ORDER BY TB.NAME
