CREATE TABLE TB_MESES(DT_MES SMALLDATETIME)

DECLARE @COUNT AS INT
DECLARE @DATEAUX AS SMALLDATETIME

SET @COUNT = 0
SET @DATEAUX = CONVERT(SMALLDATETIME, '01/01/2000', 103)

WHILE (@COUNT < (12*20))
BEGIN
	SET @COUNT = @COUNT+1
	INSERT INTO TB_MESES VALUES(@DATEAUX)
	SET @DATEAUX = DATEADD(MONTH, 1, @DATEAUX)
END

SELECT * FROM TB_MESES ORDER BY DT_MES