-- SQL VERSION
SELECT  CAST(SERVERPROPERTY('productversion') AS VARCHAR(254)) AS Versao,
CAST(SERVERPROPERTY ('productlevel') AS VARCHAR(254)) AS Level,
CAST(SERVERPROPERTY ('edition') AS VARCHAR(254)) AS Edicao

