IF(OBJECT_ID('dbo.USERS') IS NOT NULL)
	DROP TABLE dbo.USERS
		
CREATE TABLE USERS(
	ID INT IDENTITY PRIMARY KEY,
	LOGIN VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(255) ,
	PASSWORD VARCHAR(512) NOT NULL,
	ACTIVATED BIT,
	CREATED DATETIME2,
	UPDATED DATETIME2 

)


IF(OBJECT_ID('dbo.FEEDBACKS') IS NOT NULL)
	DROP TABLE dbo.FEEDBACKS
		
CREATE TABLE FEEDBACKS(
	ID INT IDENTITY PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(255) ,
	Description VARCHAR(512) NOT NULL,
	ACTIVATED BIT,
	CREATED DATETIME2,
	UPDATED DATETIME2 

)