// Generated by CoffeeScript 1.8.0
var App, teste;

teste = "";

App = (function() {
  function App() {}

  App.main = function(rtc) {
    this.rtc = rtc;
    this.connect();
    return document.getElementById("send").onclick = function() {
      return App.send();
    };
  };

  App.connect = function() {
    this.rtc.setPeerListener(this.addMessage);
    this.rtc.setRoomOccupantListener(this.showPeople);
    return this.rtc.connect("test-app", this.loginSuccess, this.loginFailure);
  };

  App.loginSuccess = function(easyrtcid) {
    this.easyrtcid = easyrtcid;
    return document.getElementById("meuId").innerHTML = "I am " + this.easyrtcid;
  };

  App.loginFailure = function(errorCode, message) {
    this.rtc.showError(errorCode, message);
    return console.log("Erro " + message);
  };

  App.addMessage = function(who, msgType, content) {
    console.log("peeer");
    content = content.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br />");
    return document.getElementById("conversa").innerHTML += "<b>" + who + ":</b>&nbsp;" + content + "<br />";
  };

  App.send = function() {
    var text, userRtcId;
    userRtcId = document.getElementById("peaple").value;
    text = document.getElementById("message");
    this.rtc.sendDataWS(userRtcId, "message", text.value);
    this.addMessage("Me", "message", text.value);
    return text.value = "";
  };

  App.showPeople = function(roomName, occupants, isPrimary) {
    var allClients, id, option, _results;
    allClients = document.getElementById("peaple");
    while (allClients.hasChildNodes()) {
      allClients.removeChild(allClients.lastChild);
    }
    teste = occupants;
    _results = [];
    for (id in occupants) {
      option = document.createElement("option");
      option.value = App.rtc.idToName(id);
      option.innerHTML = id;
      _results.push(document.getElementById("peaple").appendChild(option));
    }
    return _results;
  };

  return App;

})();

window.onload = function() {
  return App.main(easyrtc);
};
