// Generated by CoffeeScript 1.8.0
var Server, easyrtc, express, http, io;

http = require('http');

io = require('socket.io');

express = require('express');

easyrtc = require('easyrtc');

Server = (function() {
  function Server() {
    this.setUp();
  }

  Server.prototype.setUp = function() {
    var err, httpApp, socketServer, webServer;
    try {
      httpApp = express();
      httpApp.set('port', process.env.PORT || 3000);
      httpApp.use(express["static"]("" + __dirname + "/"));
      webServer = http.createServer(httpApp).listen(process.env.PORT || 3000);
      socketServer = io.listen(webServer, {
        'log level': 1
      });
      return easyrtc.listen(httpApp, socketServer);
    } catch (_error) {
      err = _error;
      return console.error(err.message, err.stack);
    }
  };

  return Server;

})();

new Server;
