"""Subclass of MainFrameBase, which is generated by wxFormBuilder."""

import wx
import gui
import serial
import time
from Queue import Queue
import threading

# Implementing MainFrameBase
class MainFrame( gui.MainFrameBase ):
	Fila = Queue(0)

	def __init__( self, parent ):
		gui.MainFrameBase.__init__( self, parent )
		self.Fila = Queue(0)

	# Handlers for MainFrameBase events.
	def myH1( self, event ):
		self.Fila.put('q')
		pass
	
	def myH2( self, event ):
		self.Fila.put('w')
		pass
	
	def myV11( self, event ):
		self.Fila.put('e')
		pass
	
	def myV12( self, event ):
		self.Fila.put('r')
		pass
	
	def myV21( self, event ):
		self.Fila.put('t')
		pass
	
	def myV22( self, event ):
		self.Fila.put('y')
		pass
	
	def myPinca( self, event ):
		self.Fila.put('a')
		pass
	
	def myFecha( self, event ):
		self.Fila.put('s')
		pass
	
	def myLerKey( self, event ):
		nASC=event.GetKeyCode()

		if (nASC <= 0 or nASC > 255):
			return

		x = chr(nASC).lower() 
		

		if x == "a":
			self.Fila.put(x)

		elif x == "s":
			self.Fila.put(x)

		elif x == "q":        
			self.Fila.put(x)

		elif x == "w":     	        
			self.Fila.put(x)

		elif x == "e":
			self.Fila.put(x)

		elif x == "r": 
			self.Fila.put(x)

		elif x == "t":
			self.Fila.put(x)

		elif x == "y":
			self.Fila.put(x)

		self.txtR.SetValue('LENDO...')
		#print(self.Fila.qsize())
		pass

	
	
