/*
 * JS for Products generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '984dbf1e-c821-47dc-95fa-b4ad0af4e55d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Stores",
    "location": "Stores.html"
}, {
    "name": "Products",
    "location": "Products.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
},{
    "name": "Tickets",
    "location": "Tickets.html"
}
];

function Products_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblStore': 'Products_lblStore',
        'lstProd': 'Products_lstProd',
        'mobilecheckbox': 'Products_mobilecheckbox'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Products';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Products_onLoad = function() {
            Products_elementsExtraJS();

            Products_deviceEvents();
            Products_windowEvents();
            Products_elementsEvents();

            $('#Products_lblStore').empty().html(window.storeName);

            var template = '<li class="Products_mobilelistitem_3 ui-li-has-thumb"   data-icon="carat-r"> \
                        <a id="Products_mobilelistitem_{n}" name="mobilelistitem_{n}" dsid="mobilelistitem_{n}" tabindex="{n}" class="Products_mobilelistitem_3 ui-btn"> \
                        <img style="width:80px; height:80px; float:right;" src="{img}" /> \
                        <h3>{name}</h3><p> \
                        <span style="float:right; font-size: 18px;">R$ {price}</span> \
                        <input type="button" value="-"" class="qtyminus" field="quantity{n}" /> \
    <input type="text" data-price="{price}" data-value="{value}" name="quantity{n}" value="0" class="qty" /> \
    <input type="button" value="+" class="qtyplus" field="quantity{n}" /> \
                        </p></a></li>';
                   
              $.mobile.loading( "show", {
                        text: "Loading...",
                        textVisible: true,
                        theme: $.mobile.loader.prototype.options.theme,
                        textonly: false,
                        html: ''
                });       
            

            $.get('http://carteen.azurewebsites.net/api/Product?idloja='+window.storeId, function(data){
                 $.each(data,function(i, e){
                    var item = $(
                        template
                            .replace(/{n}/g, i)
                            .replace('{name}', e.Name )
                            .replace('{value}', e.Id )
                            .replace('{img}', e.Picture !== '' ? e.Picture : "http://www.turquesamotel.com.br/img/icon_cardapio.png")
                            .replace(/{price}/g,parseFloat(Math.round(e.Price * 100) / 100).toFixed(2)) 
                        );

            

                    $('#Products_lstProd').append(item);
                     $.mobile.loading( "hide");                    
                 });

                              // This button will increment the value
                    $('.qtyplus').click(function(e){
                        // Stop acting like a button
                        e.preventDefault();
                        // Get the field name
                        fieldName = $(this).attr('field');
                        // Get its current value
                        var currentVal = parseInt($('input[name='+fieldName+']').val());
                        // If is not undefined
                        if (!isNaN(currentVal)) {
                            // Increment
                            $('input[name='+fieldName+']').val(currentVal + 1);
                        } else {
                            // Otherwise put a 0 there
                            $('input[name='+fieldName+']').val(0);
                        }
                           totaliza();
                    });
                    // This button will decrement the value till 0
                    $(".qtyminus").click(function(e) {
                        // Stop acting like a button
                        e.preventDefault();
                        // Get the field name
                        fieldName = $(this).attr('field');
                        // Get its current value
                        var currentVal = parseInt($('input[name='+fieldName+']').val());
                        // If it isn't undefined or its greater than 0
                        if (!isNaN(currentVal) && currentVal > 0) {
                            // Decrement one
                            $('input[name='+fieldName+']').val(currentVal - 1);
                        } else {
                            // Otherwise put a 0 there
                            $('input[name='+fieldName+']').val(0);
                        }

                        totaliza();
                    });

                    $('.qty').change(totaliza);
    
            });


            $('#btnComprar').click(function(e){
                e.preventDefault();

                var userId = 0;
                var itens = new Array();


                $('#Products_lstProd :input[type="text"]').each(function(i, e){
                    
                    if (Number( $(e).val() > 0 )){
                        var ee = new Object();

                        ee.Amount = Number( $(e).val());
                        ee.IdProduct = $(e).data('value');

                        itens.push(ee);
                    }

                });

                if (itens.length > 0){
                    saleData = {  'userid' : userId, 'itens': JSON.stringify(itens) };   
                         $.ajax({
                            type: "POST",
                            url: "http://carteen.azurewebsites.net/api/Sale",
                            data: saleData,
                            success: function( data ) {
                                if (data.indexOf("Error:")===-1)
                                {
                                    Apperyio.navigateTo('Tickets', {
                                    transition: 'slide',
                                    reverse: false});
                                }
                                else
                                {
                                    $('#notif').empty().css("color","red").slideDown().append(data);
                                }
                            },
                            error: function(){
                             $('#notif').empty().css("color","red").slideDown().append("server error");
                            },
                            dataType: "json",
                            traditional: true
                        });

                      
                }
                   

            });
        };

    // screen window events


    function Products_windowEvents() {

        $('#Products').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    function totaliza()
    {
        var total = 0;
        var itens = 0;
        $('#Products_lstProd :input[type="text"]').each(function(i, e){
            try {
                total +=  Number($(e).data('price'))*Number($(e).val());
                itens+= Number($(e).val());
            }
            catch(err) {}            
        });

        $('#Products_lblTotal span:eq(0)').text( 
            itens+" itens - "+
          " R$ "+parseFloat(Math.round(total * 100) / 100).toFixed(2))
    }

    // device events


    function Products_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Products_elementsExtraJS() {
        // screen (Products) extra code

    };

    // screen elements handler


    function Products_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#Products").on("pagebeforeshow", "#Products", function(event, ui) {
        Apperyio.CurrentScreen = "Products";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Products_onLoad();
};

$(document).off("pagecreate", "#Products").on("pagecreate", "#Products", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Products_js();
});


