/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '984dbf1e-c821-47dc-95fa-b4ad0af4e55d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Stores",
    "location": "Stores.html"
}, {
    "name": "NewUser",
    "location": "NewUser.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Contact",
    "location": "Contact.html"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_5': 'startScreen_mobilegrid_5',
        'mobilegridcell_6': 'startScreen_mobilegridcell_6',
        'mobilegridcell_7': 'startScreen_mobilegridcell_7',
        'mobileimage_4': 'startScreen_mobileimage_4',
        'mobilegridcell_10': 'startScreen_mobilegridcell_10',
        'html_30': 'startScreen_html_30',
        'txtLogin': 'startScreen_txtLogin',
        'txtPass': 'startScreen_txtPass',
        'btnLogin': 'startScreen_btnLogin',
        'btnSign': 'startScreen_btnSign',
		'btnContact': 'startScreen_btnContact',
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

		     $(document).off("click", '#startScreen_mobileheader [name="btnContact"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Contact', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobileheader [name="btnContact"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="btnLogin"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Stores', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="btnLogin"]');
        $(document).off("click", '#startScreen_mobilecontainer [name="btnSign"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('NewUser', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="btnSign"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});