USE cursosql

-- Refaz o LOG
ALTER DATABASE CURSOSQL REBUILD LOG ON (NAME=CURSOSQL,FILENAME=N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\Data\CURSOSQL_LOG.LDF') 
GO
-- Muda database de volta para Multi User
ALTER DATABASE CURSOSQL SET  MULTI_USER WITH NO_WAIT
GO

