-- Listagem Volpe
SELECT
DS_ROTINA
, COUNT(1) QT
, DATEPART(HOUR, DH_LOG) HORA
FROM TS_LOGS 
WHERE TG_ACAO = '@' AND DH_LOG > '20120425'
GROUP BY DS_ROTINA, DATEPART(HOUR, DH_LOG)
ORDER BY HORA, QT DESC

SELECT
 COUNT(1) QT
, DATEPART(HOUR, DH_LOG) HORA
FROM TS_LOGS 
WHERE TG_ACAO = '@' AND DH_LOG > '20120425'
GROUP BY DATEPART(HOUR, DH_LOG)
ORDER BY HORA, QT DESC

SELECT
DS_ROTINA
, COUNT(1) QT
FROM TS_LOGS 
WHERE TG_ACAO = '@' AND DH_LOG > '20120425'
GROUP BY DS_ROTINA
ORDER BY QT DESC