-- Habilita estatísticas para análise de performance
SET STATISTICS IO
SET FORCEPLAN
SET SHOWPLAN_ALL
SET SHOWPLAN_TEXT
SET SHOWPLAN_XML
SET STATISTICS XML
SET STATISTICS PROFILE
SET STATISTICS TIME 
