//<-------------------------------------------------------- Navbar do snooper -------------------------------------------------------->//

document.write('<div class="navbar navbar-inverse navbar-fixed-top">')
document.write('		    <div id="teste" class="navbar-inner">')
document.write('		        <div class="container-fluid">')
document.write('		            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">')
document.write('			            <span class="icon-bar"></span>')
document.write('			            <span class="icon-bar"></span>')
document.write('			            <span class="icon-bar"></span>')
document.write('		            </a>')
document.write('		            <div class="nav-collapse collapse">')
document.write('			            <ul class="nav">')
document.write('				              <li><a href="/">Home</a></li>')
document.write('				              <li><a href="/about/">About</a></li>')
document.write('				              <li><a href="/group/">Group</a></li>')
document.write('				              <li><a href="/contact/">Contact</a></li>')
document.write('				        </ul>')
document.write('		          	</div>')
document.write('		        </div>')
document.write('		    </div>')
document.write('	    </div>')

