// Generated by CoffeeScript 1.8.0
require(["vendor/preloadjs-0.6.0.min"], function(preload) {
  var queue;
  queue = new createjs.LoadQueue;
  queue.on("complete", function(evt) {
    console.log('carregou!!');
    console.log(evt);
    return window.URL.createObjectURL(queue.getResult("video"));
  }, this);
  queue.on("progress", function(evt) {
    return console.log("progress: " + evt.progress + ", total: " + evt.total + ", loaded: " + evt.loaded);
  }, this);
  return queue.loadFile({
    id: "video",
    src: "assets/video/exagerado_p1.mp4",
    type: "video"
  });
});
