/*
 * JS for Contact generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '984dbf1e-c821-47dc-95fa-b4ad0af4e55d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Stores",
    "location": "Stores.html"
}, {
    "name": "Contact",
    "location": "Contact.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function Contact_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'txtName': 'Contact_txtName',
        'txtEmail': 'Contact_txtEmail',
        'mobilelabel_5': 'Contact_mobilelabel_5',
        'txtText': 'Contact_txtText',
        'btnSend': 'Contact_btnSend'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Contact';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Contact_onLoad = function() {
            Contact_elementsExtraJS();

            Contact_deviceEvents();
            Contact_windowEvents();
            Contact_elementsEvents();

            $('#Contact_btnSend').click(function(){
                if(!validaForm())
                {
                    $('#notif').slideDown();
                } 
                else
                {
                    var form = {
                        Name :  $('#Contact_txtName').val().trim(),
                        Email : $('#Contact_txtEmail').val().trim(),
                        Description : $('#Contact_txtText').val().trim()
                    }
                    _self = $(this);
                     _self.addClass('ui-disabled');
                    $.post( "http://carteen.azurewebsites.net/api/Feedback", form)
                      .done(function( data ) {
                            if (data.indexOf("Error:")>-1)
                            {
                                data = data.replace("Error:","*");  
                                $(':input').css("border","none");
                                $('#notif').empty().css("color","red").slideDown().append(data);
                            }
                            else
                            {
                              $(':input').val('');
                              $('#notif').empty().css("color","green").slideDown().append("Sucessifull sent feedback!!<br>");
                              $(':input').css("border","none");
                            }
                            _self.removeClass('ui-disabled');
                    })
                    .fail(function(){
                         _self.removeClass('ui-disabled'); 
                     });

                  
                }
            })


        };

    // screen window events
    function validaForm()
    {
        var nome = $('#Contact_txtName');
        var valido  = true;
        $('#notif').empty();

        if (nome.val().trim()==''){
            $('#notif').css("color","red").append("*Fill required field name<br>");
            nome.css("border","solid 1px red");
            valido=false;
        }


         nome = $('#Contact_txtEmail');

        if (nome.val().trim()==''){
            $('#notif').css("color","red").append("*Fill required field email<br>");
            nome.css("border","solid 1px red");
            valido=false;
        }

         nome = $('#Contact_txtText');

        if (nome.val().trim()==''){
            $('#notif').css("color","red").append("*Fill required field text<br>");
            nome.css("border","solid 1px red");
            valido=false;
        }

        return valido;

    }


    function Contact_windowEvents() {

        $('#Contact').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Contact_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Contact_elementsExtraJS() {
        // screen (Contact) extra code

    };

    // screen elements handler


    function Contact_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#Contact").on("pagebeforeshow", "#Contact", function(event, ui) {
        Apperyio.CurrentScreen = "Contact";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Contact_onLoad();
};

$(document).off("pagecreate", "#Contact").on("pagecreate", "#Contact", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Contact_js();
});