/*
 * JS for NewUser generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '984dbf1e-c821-47dc-95fa-b4ad0af4e55d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Stores",
    "location": "Stores.html"
}, {
    "name": "NewUser",
    "location": "NewUser.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function NewUser_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_4': 'NewUser_mobilelabel_4',
        'txtLogin': 'NewUser_txtLogin',
        'mobilelabel_6': 'NewUser_mobilelabel_6',
        'txtPass': 'NewUser_txtPass',
        'mobilelabel_7': 'NewUser_mobilelabel_7',
        'txtConfirm': 'NewUser_txtConfirm',
        'mobilelabel_10': 'NewUser_mobilelabel_10',
        'mobiletextinput_9': 'NewUser_mobiletextinput_9',
        'btnNext': 'NewUser_btnNext'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'NewUser';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var NewUser_onLoad = function() {
            NewUser_elementsExtraJS();

            NewUser_deviceEvents();
            NewUser_windowEvents();
            NewUser_elementsEvents();
        };

    // screen window events


    function NewUser_windowEvents() {

        $('#NewUser').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function NewUser_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function NewUser_elementsExtraJS() {
        // screen (NewUser) extra code

    };

    // screen elements handler


    function NewUser_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#NewUser").on("pagebeforeshow", "#NewUser", function(event, ui) {
        Apperyio.CurrentScreen = "NewUser";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    NewUser_onLoad();
};

$(document).off("pagecreate", "#NewUser").on("pagecreate", "#NewUser", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    NewUser_js();
});