/*
 * JS for Stores generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '984dbf1e-c821-47dc-95fa-b4ad0af4e55d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Stores",
    "location": "Stores.html"
}, {
    "name": "NewUser",
    "location": "NewUser.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
},
 {
    "name": "Products",
    "location": "Products.html"
},
{
    "name": "Tickets",
    "location": "Tickets.html"
}
];

function Stores_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'btnLogOut': 'Stores_btnLogOut',
        'mobilelist_2': 'Stores_mobilelist_2',
        'mobilelistitem_3': 'Stores_mobilelistitem_3',
        'mobilelistitembutton_4': 'Stores_mobilelistitembutton_4',
        'mobilelistitem_5': 'Stores_mobilelistitem_5',
        'mobilelistitembutton_6': 'Stores_mobilelistitembutton_6',
        'mobilelistitem_7': 'Stores_mobilelistitem_7',
        'mobilelistitembutton_8': 'Stores_mobilelistitembutton_8',
        'mobilenavbar_11': 'Stores_mobilenavbar_11',
        'navCanteens': 'Stores_navCanteens',
        'navTickets': 'Stores_navTickets'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Stores';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Stores_onLoad = function() {

        $('#Stores_navTickets').click(function(){
             Apperyio.navigateTo('Tickets', {
                                    transition: 'slide',
                                    reverse: false});
            
        });

         $.mobile.loading( "show", {
                        text: "Loading...",
                        textVisible: true,
                        theme: $.mobile.loader.prototype.options.theme,
                        textonly: false,
                        html: ''
                });
        
            Stores_elementsExtraJS();

            Stores_deviceEvents();
            Stores_windowEvents();
            Stores_elementsEvents();

            

                var template = '<li data-value="{id}" class="Stores_mobilelistitem_3 ui-li-has-thumb" data-icon="carat-r">\
                        <a id="Stores_mobilelistitem_3" name="mobilelistitem_3" dsid="mobilelistitem_3"\
                        tabindex="{i}"  class="Stores_mobilelistitem_3 ui-btn ui-btn-icon-right ui-icon-carat-r">\
                        <img style="width:80px; height:80px;" src="{img}" />\
                        <h3>{name}</h3>\
                        </a>\
                    </li>';

                

                $.get( "http://carteen.azurewebsites.net/api/Store", function( data ) {
                    $.each(data,function(i, e){

                        var item =  $(template
                                .replace('{id}',e.Id)
                                .replace('{img}', e.Picture!=='' ?e.Picture : 'https://bestof.longislandpress.com/images/nom_buttons/09_Restaurants.png')
                                .replace('{name}', e.Name)
                                .replace('{i}', i)
                                );

                        $(item).children('a:eq(0)').click(function(e){
                            e.preventDefault();
                            window.storeId = $(this).parent().data('value');
                            window.storeName = $(this).children('h3:eq(0)').text().trim();
                              if (!$(this).attr('disabled')) {
                                Apperyio.navigateTo('Products', {
                                    transition: 'slide',
                                    reverse: false
                              });
                            }
                        });

                        $('#Stores_mobilelist').append(item);
                    })
                     $.mobile.loading( "hide");
                });


            

        };



    // screen window events


    function Stores_windowEvents() {

        $('#Stores').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Stores_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Stores_elementsExtraJS() {
        // screen (Stores) extra code

        /* mobilelist_2 */

        listView = $("#Stores_mobilelist_2");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Stores_mobilelist_2 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_3 */

        /* mobilelistitem_5 */

        /* mobilelistitem_7 */

    };

    // screen elements handler


    function Stores_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Stores_mobileheader [name="btnLogOut"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'slide',
                        reverse: true
                    });

                }
            },
        }, '#Stores_mobileheader [name="btnLogOut"]');

    };

    $(document).off("pagebeforeshow", "#Stores").on("pagebeforeshow", "#Stores", function(event, ui) {
        Apperyio.CurrentScreen = "Stores";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Stores_onLoad();
};

$(document).off("pagecreate", "#Stores").on("pagecreate", "#Stores", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Stores_js();
});