/*
 * JS for Tickets generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '984dbf1e-c821-47dc-95fa-b4ad0af4e55d';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Stores",
    "location": "Stores.html"
}, {
    "name": "Tickets",
    "location": "Tickets.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function Tickets_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_5': 'Tickets_mobilebutton_5',
        'lstTickets': 'Tickets_lstTickets',
        'mobilelistitem_3': 'Tickets_mobilelistitem_3',
        'mobilelistitembutton_4': 'Tickets_mobilelistitembutton_4'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Tickets';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Tickets_onLoad = function() {
            Tickets_elementsExtraJS();
            Tickets_deviceEvents();
            Tickets_windowEvents();
            Tickets_elementsEvents();


            var template = 
                        '<li class="Tickets_mobilelistitem_3" data-icon="none"> \
                        <a id="Tickets_mobilelistitem_{n}" name="mobilelistitem_{n}" dsid="mobilelistitem_3" tabindex="{n}" class="Tickets_mobilelistitem_3 ui-btn ui-btn-icon-right ui-icon-none"> \
                        <div class="qr" style="width:150px; height:150px; display:block; margin:0px auto;"></div> \
                        <br style="clear:both;" /> \
                       <div>{store}<br />{ticket}</div> \
                        <span style="">R$ {price}</span> \
                        </a> \
                    </li>';

      

             $.get('http://carteen.azurewebsites.net/api/Sale?userid=0', function(data){
                
                 $.each(data,function(i, e){

                    if (e.Delivered == false)
                    {
                        var item = $(
                            template
                                .replace(/{n}/g, i)
                                .replace('{store}', e.StoreName )
                                .replace('{ticket}', e.Ticket )
                                .replace('{price}', parseFloat(Math.round(e.Total * 100) / 100).toFixed(2) )
                                
                            );

                        item.find('.qr').qrcode({
                            text    : e.Ticket ,
                            width: 150,
                            height: 150
                        }); 

                          $('#Tickets_lstTickets').append(item);
                    }
                        


                 });
             });

        };

    // screen window events


    function Tickets_windowEvents() {

        $('#Tickets').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Tickets_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Tickets_elementsExtraJS() {
        // screen (Tickets) extra code

        /* lstTickets */

        listView = $("#Tickets_lstTickets");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Tickets_lstTickets .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_3 */

    };

    // screen elements handler


    function Tickets_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Tickets_mobileheader [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Stores', {
                        transition: 'slide',
                        reverse: true
                    });

                    setTimeout(function(){
                         window.location = window.location;
                    }, 1000);
                }
            },
        }, '#Tickets_mobileheader [name="mobilebutton_5"]');

    };

    $(document).off("pagebeforeshow", "#Tickets").on("pagebeforeshow", "#Tickets", function(event, ui) {
        Apperyio.CurrentScreen = "Tickets";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Tickets_onLoad();
};

$(document).off("pagecreate", "#Tickets").on("pagecreate", "#Tickets", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Tickets_js();
});