
DECLARE @CURRENT_COLLATE AS VARCHAR(1000)
SET @CURRENT_COLLATE = CONVERT(VARCHAR(1000),(DATABASEPROPERTYEX(DB_NAME(), 'COLLATION')))
DECLARE CAMPOS CURSOR FOR
SELECT
      UPPER(COL.TABLE_NAME) AS DS_TABELA,
      UPPER(COL.COLUMN_NAME) AS DS_COLUNA,
      UPPER(COL.DATA_TYPE) AS DS_TIPO,
      COALESCE(COL.CHARACTER_MAXIMUM_LENGTH,0) AS NR_LEN
FROM INFORMATION_SCHEMA.COLUMNS COL
WHERE
      CONVERT(VARCHAR(1000), COL.COLLATION_NAME) <> @CURRENT_COLLATE
ORDER BY DS_TABELA,DS_COLUNA   
 
OPEN CAMPOS
DECLARE @tablename SYSNAME
DECLARE @column_name SYSNAME
DECLARE @column_type SYSNAME
DECLARE @column_len INTEGER
DECLARE @COMMAND AS VARCHAR(1000)
FETCH NEXT FROM CAMPOS INTO @tablename,@column_name,@column_type,@column_len
WHILE (@@FETCH_STATUS <> -1) BEGIN
	IF (@@FETCH_STATUS <> -2) BEGIN   
      SELECT @tablename = RTRIM(@tablename)
		  BEGIN TRY

  			SET @COMMAND =('ALTER TABLE ' + @tablename + ' ALTER COLUMN ' +
  				 @column_name + ' ' + @column_type +
  					(CASE WHEN @column_len = 0 OR @column_type = 'TEXT' THEN '' ELSE '('+CAST(@column_len AS VARCHAR(10))+')' END)+
  					' ' + ' COLLATE ' + @CURRENT_COLLATE
  			)
  			
  			exec(@COMMAND)
		  END TRY
		  BEGIN CATCH
			PRINT @tablename + '- erro!: ' + ERROR_MESSAGE() ;
		  END CATCH;
	END
   FETCH NEXT FROM CAMPOS INTO @tablename,@column_name,@column_type,@column_len
END
CLOSE CAMPOS
DEALLOCATE CAMPOS

 